version: "3.8"

services:
  # 1. The Backend API
  backend:
    build: ./server
    container_name: rentacar_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - rentacar-network

  # 2. The Frontend Interface
  frontend:
    build:
      context: ./client
      # We pass the API URL so Vite can bake it into the HTML
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: rentacar_frontend
    ports:
      # AWS Port 80 -> Nginx Port 80
      - "80:80"
    depends_on:
      - backend
    networks:
      - rentacar-network

networks:
  rentacar-network:
    driver: bridge
